### ISSUE TITLE
lose libmemcached.dll

### ISSUE THREAD

**Issue by tianyiw2013** [lifenglsf/php_memcached_dll#1]
---------------------------
php.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 libmemcached.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------

**Comment by lifenglsf** [comment]
复制对应系统版本的libmemcached.dll到windows目录，libmemcached.dll和php_memcached.dll 放在一起的

**Comment by tianyiw2013** [comment]
啊。。php7.4文件夹里没有这个 libmemcached.dll文件，我试试7.3的

**Comment by lifenglsf** [comment]
不好意思，7.4的dll缺失了，刚刚补上了。

**Comment by tianyiw2013** [comment]
丢失 VCRUNTIME140D.dll，我尝试装vc2015，按照程序提示我已经装了更新版本了，不能安装

**Comment by lifenglsf** [comment]
系统的信息看下

**Comment by lifenglsf** [comment]
看下system32或者syswow64下有没有VCRUNTIME140D.dll这个文件

**Comment by tianyiw2013** [comment]
64位win7
vc++2005、2008、2010/2012/2013/2015-2019、2017   x64、x86都装了  
没有VCRUNTIME140D.dll这个文件，有vcruntime140.dll；
我从网上下了一个VCRUNTIME140D.dll，不行

**Comment by tianyiw2013** [comment]
我知道了，stackoverflow了一下，

> a release version which does NOT end with a d - for example: vcruntime140.dll
a debug version which ends with a d - for example: vcruntime140d.dll

你应该是用的debug编译出来的，我没有编译环境，所以缺vcruntime140d.dll

**Comment by tianyiw2013** [comment]
从网上找了个vcruntime140d.dll复制到system32解决了vcruntime140d.dll不存在问题；
然后提示缺ucrtbased.dll，复制了你提供的ucrtbased.dll后，不提示缺少dll了，提示下面内容：

> 
> D:\Program Files\php-7.4.0-nts-Win32-vc15-x64>php -v
> PHP Warning:  PHP Startup: Unable to load dynamic library 'php_memcached.dll' (tried: ext\php_memcached.dll (%1 ��������
> ������� Win32 ���������������), ext\php_php_memcached.dll.dll (���������������������������)) in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library 'php_memcached.dll' (tried: ext\php_memcached.dll (%1 不是有效的 Win32 应
> 用程序。), ext\php_php_memcached.dll.dll (找不到指定的模块。)) in Unknown on line 0
> PHP 7.4.0 (cli) (built: Nov 27 2019 10:13:59) ( NTS Visual C++ 2017 x64 )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by lifenglsf** [comment]
是的，我等下编译成release的版本

**Comment by lifenglsf** [comment]
php.ini中怎么添加的？

**Comment by tianyiw2013** [comment]
php.ini应该没问题，extension=php_memcached.dll

> tried: ext\php_memcached.dll (%1 不是有效的 Win32 应用程序。)

说明php已经加载到这个dll了

**Comment by lifenglsf** [comment]
php7.3，7.4添加扩展，写extension=memcached

**Comment by tianyiw2013** [comment]
好的， 我试试

**Comment by lifenglsf** [comment]
可以了吗

**Comment by tianyiw2013** [comment]
还是不行呀

> Warning: PHP Startup: Unable to load dynamic library 'memcached' (tried: ext\memcached (找不到指定的模块。), ext\php_memcached.dl
> l (%1 不是有效的 Win32 应用程序。)) in Unknown on line 0
> PHP 7.4.0 (cli) (built: Nov 27 2019 10:13:59) ( NTS Visual C++ 2017 x64 )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies

PHP7.4添加扩展支持`extension=memcached`和`extension=php_memcached.dll`两种都行，php会自动判断dll是否存在。


实现不行就算了，用redis吧 ~_~

辛苦了，谢谢

**Comment by lifenglsf** [comment]
配置extension_dir,我装了个虚拟机安装的是win7 64位的，发现不配置extension_dir会默认到c:\php\ext这个目录下，这个目录肯定是没有扩展的。

**Comment by tianyiw2013** [comment]
我的ini配置应该没问题的，上面两次dll报错提示里提示已经找到dll了。

> tried: ext\php_memcached.dll (%1 不是有效的 Win32 应用程序。)

> tried: ext\memcached (找不到指定的模块。), ext\php_memcached.dll (%1 不是有效的 Win32 应用程序。))

上面两行是php给出的警告，tried已经尝试过 ext\php_memcached.dll 原因(%1 不是有效的 Win32 应用程序。) **说明扩展已经识别到了，但是dll无效**

不知道什么问题，很奇怪-_-

**Comment by lifenglsf** [comment]
你把memcache的扩展先不加上，你看下php的extension_dir是在哪里，我的虚拟机是新装的系统，里面还是比较干净的，是可以正常识别的。libmemcached.dll已经更新位release版本了。你可以下载最新的再试下。phpinfo中会显示extension_dir的位置

**Comment by tianyiw2013** [comment]
ok了，下载了最新的libmemcached.dll没问题了。

**Comment by tianyiw2013** [comment]
我直接把libmemcached.dll和ucrtbased.dll放到php目录了，不放到window目录下也是可以的。

问题已解决，谢谢了。
