### ISSUE TITLE
请问支持PHP7.4.33版本了吗

### ISSUE THREAD

**Issue by jqljing** [lifenglsf/php_memcached_dll#10]
目前下载已有的3.20.对应的PHP7.4 ts_X64版本，放到Visual C++ 2019编译的PHP7.4.33版本下使用，报PHP Warning: PHP Startup: Unable to load dynamic library 'memcached' (tried: E:/2jiplat/php/ext/memcached (找不到指定的模块。), E:/2jiplat/php/ext/php_memcached.dll (找不到指定的模块。)) 错误，无法加载

**Comment by lifenglsf** [comment]
应该是支持7.4.33的。下载的php7.4.33是ts版本吗，php7.4.33是哪里下载，给个地址我可以验证下。

**Comment by jqljing** [comment]
> 应该是支持7.4.33的。下载的php7.4.33是ts版本吗，php7.4.33是哪里下载，给个地址我可以验证下。

这边下载的 https://windows.php.net/download#php-7.4-ts-vc15-x64

**Comment by lifenglsf** [comment]
@jqljing 我下载7.4.33试了basic 版本的3.2.0的memcached，是没有问题的,memcached需要用到libmemcached.dll这个文件，这个文件可以放到c盘windows目录下，也可以放到编译后的php的根目录下，我命令行是的效果是把libmemcached.dll放到编译的php的根目录下的
![image](https://user-images.githubusercontent.com/1817560/229480736-bd5ca680-240a-44ef-899d-f5f337498307.png)
不清楚是不是你没有配置php扩展放置的目录,默认的配置会有问题的，需要把php.ini中的extension_dir配置成实际的php扩展的目录地址。可以使用我命令行使用的命令看下效果。另外如果要求支持igbinary或者msgpack需要单独下载对应的dll文件。
```F:\phpmemcachedwin\phpsource\php-7.4.33-Win32-vc15-x64>php.exe -v
PHP 7.4.33 (cli) (built: Nov  2 2022 16:00:55) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

F:\phpmemcachedwin\phpsource\php-7.4.33-Win32-vc15-x64>php.exe -dextension_dir=ext -dextension=memcached
^C
F:\phpmemcachedwin\phpsource\php-7.4.33-Win32-vc15-x64>php.exe -dextension_dir=ext -dextension=memcached --ri=memcached

memcached

memcached support => enabled
Version => 3.2.0
libmemcached version => 1.0.18
SASL support => no
Session support => yes
igbinary support => no
json support => yes
msgpack support => no```

**Comment by jqljing** [comment]
> 

感谢，用basic版本并且lib文件放windows及php主目录之后确实可以了。
另外当前有支持VC16 2019以上的扩展版本吗，这边需要使用Visual C++ 2019编译的php版本

**Comment by lifenglsf** [comment]
> > 
> 
> 感谢，用basic版本并且lib文件放windows及php主目录之后确实可以了。 另外当前有支持VC16 2019以上的扩展版本吗，这边需要使用Visual C++ 2019编译的php版本

官方下载的php应该都是支持的，目前未测试php7.4，8.0等所有的小版本。如果有问题可以发issue，我这边会跟进的。另外说明下lib放到windows或者php的主目录二选一即可，如果使用php的版本同时存在x86和x64建议放到php根目录下，因为windows目录下的lib只能是32位或者64位
