### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by lipemat** [lifenglsf/php_memcached_dll#11]
Now that PHP 8.1 is reaching the end of active support, do you have compiled file that works with PHP 8.2?

Thank you.

**Comment by lifenglsf** [comment]
等待官方发新的版本，3.2.0对windows下的8.2支持还是有些问题的

**Comment by lipemat** [comment]
Is there something we can do to help move this along?

**Comment by lifenglsf** [comment]
try [8.2](https://github.com/lifenglsf/php_memcached_dll/tree/master/auto-master).
There is no new version of php-memcached

**Comment by lipemat** [comment]
> try [8.2](https://github.com/lifenglsf/php_memcached_dll/tree/master/auto-master).

This is working well. 

Thank you so much!
