### ISSUE TITLE
About ‘SASL support’ in WINDOWS platform

### ISSUE THREAD

**Issue by xinjiawei** [lifenglsf/php_memcached_dll#13]
Hi, i tested the official version memcahced extension in pecl.php.net/package/memcached, the ‘SASL support’  is NO too, jsut like your version, why ‘SASL support’ is NO, is it not supported in WINDOWS? Thanks.

**Comment by lifenglsf** [comment]
[config.w32](https://github.com/php-memcached-dev/php-memcached/blob/master/config.w32),no enable_sasl option.try to submit issue to official repo
