### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by irfanappify** [lifenglsf/php_memcached_dll#4]
Php 7.4 TS x64
using XAMPP
copied extension in 
XAMPP/PHP/ext like all other extensions
added to php.ini extension = php_memcached.dll
copied libmemcached.dll to C:Windows
getting error
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_memcached.dll' (tried: D:\xampp\php\ext\php_memcached.dll (The specified module could not be found.), D:\xampp\php\ext\php_php_memcached.dll.dll (The specified module could not be found.)) in Unknown on line 0

**Comment by lifenglsf** [comment]
I used official compied package when testing.xampp version?

**Comment by lifenglsf** [comment]
@irfanappify 

![image](https://user-images.githubusercontent.com/1817560/98324477-52ce5780-2027-11eb-9044-fca4a2f77cfa.png)
![image](https://user-images.githubusercontent.com/1817560/98324493-5feb4680-2027-11eb-964f-88949c8521a6.png)
i used php_memcached_dll 3.14 and latest xampp，works fine

**Comment by irfanappify** [comment]
What's your exactl path for "libmemcached.dll" on windows? Do you somehow need to register this DLL to windows or just copying it would work?

**Comment by lifenglsf** [comment]
copy libmemcached.dll to c:\windows directory,php_memcached.dll will auto call libmemcached.dll
