### ISSUE TITLE
PHP 8.0.0 Release

### ISSUE THREAD

**Issue by tianyiw2013** [lifenglsf/php_memcached_dll#5]
您好，麻烦编译一下PHP 8.0.0的版本，谢谢啦 😀

**Comment by lifenglsf** [comment]
https://pecl.php.net/package/memcached  等这里发布8.0的支持，稍等

**Comment by ghost** [comment]
@lifenglsf https://github.com/php-memcached-dev/php-memcached/issues/466#issuecomment-735445743
It apparently works with PHP 8.0, though not released yet.

**Comment by lifenglsf** [comment]
> @lifenglsf [php-memcached-dev/php-memcached#466 (comment)](https://github.com/php-memcached-dev/php-memcached/issues/466#issuecomment-735445743)
> It apparently works with PHP 8.0, though not released yet.

Maybe I will compile pre release in the next few weeks

**Comment by lifenglsf** [comment]
@tianyiw2013 @jonathan-rosa  i built pre-3.2.0
