### ISSUE TITLE
memcached for php8.1

### ISSUE THREAD

**Issue by stafred** [lifenglsf/php_memcached_dll#8]
please fix memcached for php8.1. *
error ` zend_parse_arg_slow@@16`

**Comment by lifenglsf** [comment]
Memcached does not yet support the official version of PHP 8。I'll try using the master branch

**Comment by lifenglsf** [comment]
i compiled file does not support php8.1     
Do you use i compiled dll file？

**Comment by stafred** [comment]
yes i tried to start server with your module for php8.1 on windows

**Comment by lifenglsf** [comment]
![image](https://user-images.githubusercontent.com/1817560/147428384-6785df01-cd4c-42e8-8460-c1afacc47d6f.png)
7.3,7.4,8.0 supported,other php version not support.I'm going to compile another pre version that supports PHP 8.1。It will take some time

**Comment by lifenglsf** [comment]
[memcached-for8.1-windows.zip](https://github.com/lifenglsf/php_memcached_dll/files/7782317/memcached-for8.1-windows.zip)
zip file only support php8.1
copy libmemcached to C:\windows

**Comment by oskarspe** [comment]
Thank you for php 8.1 build, but it seems that it doesn't have igbinary support.

**Comment by lifenglsf** [comment]
> [memcached-for8.1-windows.zip](https://github.com/lifenglsf/php_memcached_dll/files/7782317/memcached-for8.1-windows.zip) zip file only support php8.1 copy libmemcached to C:\windows

Before August 1st, I manually compiled a full version。

**Comment by lifenglsf** [comment]
> Thank you for php 8.1 build, but it seems that it doesn't have igbinary support.

Before August 1st, I manually compiled a full version。

**Comment by lifenglsf** [comment]
> Thank you for php 8.1 build, but it seems that it doesn't have igbinary support.

i compiled new release support php 8.1

**Comment by oskarspe** [comment]
Thank you. Working good with igbinary support. 👍
